GoogleCloudPlatform/opentelemetry-operations-js

packages/opentelemetry-cloud-monitoring-exporter/src/types.ts
Copied from https://github.com/census-instrumentation/opencensus-node/blob/ef5712fd3b279b0e80494322231232047b06f9e6/packages/opencensus-exporter-stackdriver/src/types.ts#L167-L261
Updates #9
Next Steps:
- Create `StackdriverMetricExporter` class, implements [MetricExporter](https://github.com/open-telemetry/opentelemetry-js/blob/6616bb17910eba2f38eef4665c717d207823b904/packages/opentelemetry-metrics/src/export/types.ts#L54-L66)
- Add transfrom logic to convert OpenTelemetry `MetricRecord` format to Stackdriver `MetricDescriptor` and `TimeSeries` format.
- Unit Tests
- Documentation
=> Add Stackdriver MetricDescriptor and TimeSeries types

packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts, packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts, packages/opentelemetry-cloud-monitoring-exporter/test/transform.test.ts
`LabelSet` API is removed from `v0.6.1`. See: https://github.com/open-telemetry/opentelemetry-js/releases/tag/v0.6.0
=> upgrade to opentelemetry v0.6.1

packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts
This PR is regarding Issue #77. 
Within transformMetric(...), I cast the variable to a string. This makes the behavior of the Google Cloud Monitoring exporter consistent with Prometheus. For example, a user can create `labels = {pid: process.pid};`, as they previously could with Prometheus' exporter.
All tests + linter pass. I also tested it on my local application, using both a string and an integer. 
I planned on including an additional unit test in the test file. However, I was unable to do so because the typescript mandates that the labels dictionary is {string : string}, and I cannot create a test case that is {string: number}
=> fix: Cast integer label values to string

packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts, packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts, packages/opentelemetry-cloud-monitoring-exporter/src/utils.ts, packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts
**Description:**
* Adds a batch limit of 200 to TimeSeries sent due to limit in Stackdriver backend.
**Smaller changes:**
* Adds helper function for partitioning batches
* Fixes misleading comment in `transform.ts`
* Fixes parameter mismatch error being throw by `metricDescriptors` spy
**Previous implementation in OpenCensus:**
https://github.com/census-instrumentation/opencensus-node/pull/644
Fixes #87
=> fix: Stackdriver batch limit for TimeSeries

packages/opentelemetry-cloud-trace-exporter/src/transform.ts, packages/opentelemetry-cloud-trace-exporter/test/transform.test.ts
Updates `AGENT_LABEL_VALUE` in `transform.ts` and the corresponding unit test.
Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/99
=> fix: update agent label name

packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts, packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts, packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts, packages/opentelemetry-cloud-monitoring-exporter/test/transform.test.ts
This PR upgrades the cloud monitoring exporter's dependency on @opentelemetry/metrics to the latest release (0.9.0).
The biggest change to @opentelemetry/metrics was the [removal](https://github.com/open-telemetry/opentelemetry-js/pull/1126) of `labelKeys` from `MetricOptions`. In response, labels are now added to GCP metrics using the metric instead of the metric descriptor as per the [GCP Docs](https://cloud.google.com/monitoring/custom-metrics/creating-metrics#md-modify)
Functions were adjusted to handle the additional `MetricKind`s that were [added](https://github.com/open-telemetry/opentelemetry-js/pull/1145)
Added some additional unit tests; all tests pass. 
Tested metric export on a GCE VM running the latest version of node.
Fixes #102
=> fix: cloud monitoring incompatibility with opentelemetry/metrics 0.9.0

packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts, packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts, packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts, packages/opentelemetry-cloud-monitoring-exporter/test/transform.test.ts
This PR is regarding Issue #79. 
Within createTimeSeries(...), I call detectResources, within @OpenTelemetry/resources. This determines whether it's an AWS EC2 Instance, a Google Cloud VM Instance, or another resource type. I convert it to a format which Stackdriver can accept.
I looked at the OpenCensus StackDriver exporter to determine the correct resource labels: https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-exporter-stackdriver/src/common-utils.ts
I also updated the versions of the dependencies to allow for resource checking. This required a minor change (altering the type of one parameter). 
I tested it locally on my Google Cloud VM Instance, and it successfully displayed metrics under the resource type "GCE VM Instance". 
Within …
=> feat: Add resource within Google Cloud Monitoring Exporter

packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/src/trace.ts, packages/opentelemetry-cloud-trace-exporter/src/transform.ts, packages/opentelemetry-cloud-trace-exporter/src/types.ts, packages/opentelemetry-cloud-trace-exporter/test/exporter.test.ts, packages/opentelemetry-cloud-trace-exporter/test/transform.test.ts
**Description**
- Adds a `cloudtrace.v2.TraceService` client to `TraceExporter` to be used to write span data to cloud trace
- Updated tests to work with the new rpc client
**Testing** 
- Passes existing unit tests
- Ran the following opentelemetry example found [here](https://github.com/open-telemetry/opentelemetry-js/tree/master/examples/grpc) modified to use the exporter in this PR, and it produced expected results
- Tested on a live instance
**Relevant Info**
- Docs for RPC service can be found [here](https://cloud.google.com/trace/docs/reference/v2/rpc/google.devtools.cloudtrace.v2#google.devtools.cloudtrace.v2.TraceService.BatchWriteSpans)
Fixes #94
=> feat: use gRPC to write spans to cloud trace

.circleci/config.yml, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts, packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/src/trace.ts, packages/opentelemetry-cloud-trace-exporter/test/exporter.test.ts, samples/trace/README.md, samples/trace/package-lock.json, samples/trace/package.json
Fixes #156 
- Removed references to `@opentelemetry/base` which was merged into `@opentelemetry/core` for 0.8.0.
- Then, upgraded all min peer/dev dependencies to be atleast `0.8.0` if they weren't already.
- Capped peer dependency versions at current `0.10.x`; will test more releases as they come out and increase minor version.
- Upgraded sample app versions and tested. `npm list` does not output any errors about peer deps.
- Added CI step to test that sample app dependencies have no errors, like unsatisfied peer deps that we previously had.
=> fix: adjust peer dep versions of OT packages

packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts, packages/opentelemetry-cloud-monitoring-exporter/src/types.ts, packages/opentelemetry-cloud-monitoring-exporter/test/transform.test.ts
Addresses: https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/101
Adding support for exporting OpenTelemetry Distribution and Histogram types as Cloud Monitoring API v3 Distributions
* Tested manually with exporting to personal GCP project
* Updated unit tests
=> feat: add support for Distributions

packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts, packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts, packages/opentelemetry-cloud-monitoring-exporter/test/transform.test.ts, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/src/transform.ts, packages/opentelemetry-cloud-trace-exporter/test/exporter.test.ts, packages/opentelemetry-cloud-trace-exporter/test/transform.test.ts, packages/opentelemetry-cloud-trace-propagator/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package.json, packages/opentelemetry-cloud-trace-propagator/src/CloudPropagator.ts, samples/trace/package-lock.json, samples/trace/package.json
Fixes #165
----
It is no longer possible to support back to v0.8.0 because of a fair number of breaking changes. As suggested in #165, this upgrades all peer dependencies to `^0.11.0`. The next release will be a "major" release (v0.5.0 per semantic versioning < v1.0.0) because of these breaking changes.
Fixes for new opentelemetry version:
- `resource.labels -> resource.attributes`
- `OTPoint` is now generic `OTPoint<PointValueType>`
- `meter.collect()` needs to now be awaited in tests. I'm not sure if it was previously not async, but the tests fail if without waiting for the promise to resolve.
- `OTMetricKind.OBSERVER` was removed …
=> feat: upgrade packages to opentelemetry version 0.11.0

packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts, packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts, packages/opentelemetry-cloud-monitoring-exporter/test/transform.test.ts, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/src/trace.ts, packages/opentelemetry-cloud-trace-exporter/test/transform.test.ts, packages/opentelemetry-cloud-trace-propagator/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package.json, packages/opentelemetry-cloud-trace-propagator/src/CloudPropagator.ts, packages/opentelemetry-cloud-trace-propagator/test/CloudPropagator.test.ts, samples/trace/package-lock.json, samples/trace/package.json
Part of #188 
Upgrade OpenTelemetry peer dependencies to v0.12.0.
- `Distribution` was removed altogether
- Some other fixes for slight API changes
- I think the codecov drop is flaky since I deleted code?
=> chore: upgrade for opentelemtry js v0.12.0

packages/opentelemetry-cloud-trace-exporter/src/transform.ts, packages/opentelemetry-cloud-trace-exporter/test/transform.test.ts
Fixes #214
list of all http attributes are here: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#common-attributes
I tried to add all of them
also note that in python they did it in this way:
https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/c3772de4cf50950f1d51685ff3bbf0e46ee026df/opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_trace/__init__.py#L367
=> fix(tracer): add http mapping attributes to transformer

package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts, packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts, packages/opentelemetry-cloud-monitoring-exporter/test/transform.test.ts, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/src/trace.ts, packages/opentelemetry-cloud-trace-exporter/test/exporter.test.ts, packages/opentelemetry-cloud-trace-exporter/test/transform.test.ts, packages/opentelemetry-cloud-trace-propagator/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package.json, packages/opentelemetry-cloud-trace-propagator/src/CloudPropagator.ts, packages/opentelemetry-cloud-trace-propagator/test/CloudPropagator.test.ts, samples/trace/package-lock.json, samples/trace/package.json
Fixes #215 
Upgrading peer/dev deps and fixing the associated breaking changes from upstream. Mainly:
- Propagator getters and setters were changed into classes and renamed
- `ExportResult` was changed into an object with separate `code` and `error` fields
- `ExportResult` enum is now `ExportResultCode` and `FAILED_RETRYABLE` was removed.
* retries were never actually implemented, so this is not a functionality change
* they decided retries should be implemented by the exporters directly, which makes sense. Tracked in #181 
- `Meter.getBatcher()` -> `Meter.getProcessor()`
- `CanonicalCode` -> `StatusCode`
- Propagators have a new `fields()` method ([see spec](https://github.com/open-telemetry/opentelemetry-specification/blob/181a1afdb201f1334fb032960bb1672cf5a0272f/specification/context/ap …
=> chore: upgrade peer/dev deps to @opentelemetry 0.14.0

packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts, packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts, packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts, packages/opentelemetry-cloud-monitoring-exporter/test/transform.test.ts, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/src/trace.ts, packages/opentelemetry-cloud-trace-exporter/src/transform.ts, packages/opentelemetry-cloud-trace-exporter/src/types.ts, packages/opentelemetry-cloud-trace-exporter/test/exporter.test.ts, packages/opentelemetry-cloud-trace-exporter/test/transform.test.ts, packages/opentelemetry-cloud-trace-propagator/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package.json, packages/opentelemetry-cloud-trace-propagator/src/CloudPropagator.ts, packages/opentelemetry-cloud-trace-propagator/test/CloudPropagator.test.ts, samples/trace/package-lock.json, samples/trace/package.json
- Metrics api moved to separate package `@opentelemetry/api-metrics`
- `setExtractedSpanContext` -> `setSpanContext`
- `getParentSpanContext` -> `getSpanContext`
- Fixed broken status mapping and added tests
=> chore: upgrade to OTel v0.16.0 packages

package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts, packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts, packages/opentelemetry-cloud-monitoring-exporter/src/types.ts, packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts, packages/opentelemetry-cloud-monitoring-exporter/test/transform.test.ts, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-propagator/package-lock.json, samples/trace/package-lock.json
- Upgrade google-auth-library to v7
- In the process, `package-lock.json` files got converted to v2 format for npm7. This is what we should use going forward, just need renovate to also genearte v2 as well.
- This requires upgrading googleapis so it can share the same google-auth-library dependency, otherwise TS complains about mismatched classes
- googleapis Cloud Monitoring API expects the payload to use a different key.
* It wasn't caught in previous upgrade because typescript doesn't check for exact types (unless you annotate at assignment??).
* It was still working anyway (seems like the code was backward compatible), but I updated it anyway
* Reworked types to catch this sort of error in future
* Also, [int64 proto fields should be sent as …
=> fix(deps): update dependency google-auth-library to v7

.github/workflows/ci.yaml, docs/releasing.md, package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package-lock.json, samples/trace/package-lock.json
- Update releasing.md instructions saying to bump `version.ts` files. This is unfortunate we need to do this and I think I can change it in the future to instead just read from package.json. I believe it was originally done this way for web compat, where you don't necessarily have the package.json file. opentelemetry-js upstream generates these files with a script, which is another option
- Regenerate package locks with `lockfileVersion` 2 again :( Added a CI check that all package locks are using the new version to prevent this in the future
=> chore: update releasing instructions, add check for lockfile v2

package-lock.json, renovate.json
I think [`:pinOnlyDevDependencies`](https://docs.renovatebot.com/presets-default/#pinonlydevdependencies) is the best way to go with renovate. It ensure that devDependencies are a specific version (also in lockfile, but [renovate recommends doing both](https://docs.renovatebot.com/dependency-pinning/#pinning-dependencies-and-lock-files)) but we can keep semver ranges for dependencies and especially peerDependencies, which users would be installing.
=> chore: configure renovate to only pin devDependencies

package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package-lock.json, samples/trace/package-lock.json
Ran
- `npm audit fix` to fix the root package lockfiles
- `npx lerna exec npm -- audit fix` to fix package lockfiles
This fixes security vulnerabilities in the locked versions
=> chore: run npm audit fix for all packages to update lock files

packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts, packages/opentelemetry-cloud-monitoring-exporter/test/transform.test.ts, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/src/transform.ts, packages/opentelemetry-cloud-trace-exporter/test/exporter.test.ts, packages/opentelemetry-cloud-trace-exporter/test/transform.test.ts, packages/opentelemetry-cloud-trace-propagator/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package.json, packages/opentelemetry-cloud-trace-propagator/src/CloudPropagator.ts, packages/opentelemetry-cloud-trace-propagator/test/CloudPropagator.test.ts, samples/trace/package-lock.json, samples/trace/package.json
Fixes #273, fixes #252
0.21.0 is the newest version of all OTel JS packages. Fixed a few renames and type breakages. Use new semantic-convention package for applicable constants.
=> upgrade dependencies to 0.21.0, fix breakages

.github/workflows/ci.yaml
- Node 15 (non LTS) is no longer supported and 16 is the current release https://nodejs.org/en/about/releases/
- I am leaving node 10 for now as most things still support it.
- Ignore cloud build CI failures for now
=> chore: update ci runs to use only current node versions

cloudbuild-e2e-gce.yaml, cloudbuild-e2e-gke.yaml, cloudbuild-e2e-local.yaml
- GCE container images are taking a little longer than previously to come up, so adjust its health check timeout to be longer
- Made the overall timeout for the test runs 20 minutes.
* There are timeouts in the actual test runner code which should stop the test before this longer timeout
* Cloud Build kills a test immediately when it times out, which is bad because we don't get to teardown the resources we created
- The `0.6.0` version has `--health-check-timeout` instead of `--healthchecktimeout`
=> chore: e2e test runner version and adjust timeouts

e2e-test-server/package-lock.json, e2e-test-server/package.json, lerna.json, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/src/version.ts, packages/opentelemetry-cloud-trace-propagator/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package.json, packages/opentelemetry-resource-util/package-lock.json, packages/opentelemetry-resource-util/package.json, samples/trace/package-lock.json, samples/trace/package.json
Release proposal https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/releases/edit/untagged-f49888a55d0fade43547
* uncaught rejected promise error in MetricExporter's export method ([#258](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/258)) ([541d3f0](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/commit/541d3f002888eb19e836e0be3961917a356fcc80))
* **deps:** update all non-major dependencies ([#255](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/255)) ([1f6423c](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/commit/1f6423ccc15b257b1674cbc6143eaf0ada2c45a2))
* **deps:** update dependency googleapis to v68 ([#249](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/iss …
=> chore: 0.10.0 release proposal

packages/opentelemetry-cloud-trace-exporter/src/transform.ts, packages/opentelemetry-cloud-trace-exporter/src/types.ts, packages/opentelemetry-cloud-trace-exporter/test/transform.test.ts
BREAKING CHANGE: add span kind is now sent with traces.
=> feat(trace-exporter)!: send span kind to cloud trace

renovate.json
Typescript version upgrades can break the build. This forces renovate to make a separate PR for Typescript upgrades to separate out breakages. This should fix the build on https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/pull/319
=> chore: configure renovate to make separate PR for typescript

README.md, e2e-test-server/package-lock.json, e2e-test-server/package.json, e2e-test-server/src/scenarios.ts, packages/opentelemetry-cloud-monitoring-exporter/README.md, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts, packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts, packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts, packages/opentelemetry-cloud-monitoring-exporter/test/transform.test.ts, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/src/trace.ts, packages/opentelemetry-cloud-trace-exporter/src/transform.ts, packages/opentelemetry-cloud-trace-exporter/test/exporter.test.ts, packages/opentelemetry-cloud-trace-exporter/test/transform.test.ts, packages/opentelemetry-cloud-trace-propagator/README.md, packages/opentelemetry-cloud-trace-propagator/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package.json, packages/opentelemetry-resource-util/package-lock.json, packages/opentelemetry-resource-util/package.json, samples/trace/README.md, samples/trace/index.js, samples/trace/package-lock.json, samples/trace/package.json
Fixes #314
Upgraded all SDK deps to `0.25.0`, including newly renamed packages:
old pkg name           | new pkg name 
-----------------------|------------------
@opentelemetry/tracing | @opentelemetry/sdk-trace-base 
@opentelemetry/node    | @opentelemetry/sdk-trace-node
@opentelemetry/metrics | @opentelemetry/sdk-metrics-base
=> fix!: rename SDK packages that were changed upstream

package-lock.json, packages/opentelemetry-cloud-trace-exporter/README.md, packages/opentelemetry-cloud-trace-exporter/src/external-types.ts, packages/opentelemetry-cloud-trace-exporter/src/trace.ts, packages/opentelemetry-cloud-trace-exporter/src/transform.ts, packages/opentelemetry-cloud-trace-exporter/test/transform.test.ts
Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/347
This PR adds support for exporting OpenTelemetry resource attributes that match a regular expression, as was [suggested](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/347#issuecomment-946881138) in the linked issue.
=> feat: add optional filter for OTel resource attributes

packages/opentelemetry-cloud-monitoring-exporter/src/external-types.ts, packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts, packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts
The underlying client library doesn't expose apiEndpoint like the trace one does, so I've named it differently (rootUrl instead of apiEndpoint) accordingly.
=> Add apiEndpoint option to cloud monitoring exporter

cloudbuild-e2e-gce.yaml
It is timing out waiting for the container to start https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/pull/371/checks?check_run_id=8621886819
If this gets much longer, we may need to investigate. I had to increase it for operations-python repo as well, but operations-go doesn't seem to have a similar problem. It could be the docker image is too large.
=> chore: increase gce integration test timeout

renovate.json
This will cause renovate to group these PRs into one:
- https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/pull/401
- https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/pull/422
peerDependency which makes it impossible to upgrade separately
=> chore: add renovate package group for all mocha lockstep versioned packages

renovate.json
This time I validated the config with `renovate_config_validator` script
=> chore: fix renovate config typo

.github/header-checker-lint.yml, packages/opentelemetry-cloud-monitoring-exporter/.eslintignore, packages/opentelemetry-cloud-monitoring-exporter/__snapshots__/instrument-snapshot.test.ts.js, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-monitoring-exporter/test/instrument-snapshot.test.ts, packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts
Adding initial snapshot testing boilerplate. More tests are added for each instrument in follow up PR #449.
----
Note I tried to use nock's [nock back](https://github.com/nock/nock#nock-back) feature but the amount of code needed to customize it was more than this PR.
=> test(monitoring-exporter): add snapshot tests

packages/opentelemetry-cloud-monitoring-exporter/__snapshots__/instrument-snapshot.test.ts.js, packages/opentelemetry-cloud-monitoring-exporter/test/instrument-snapshot.test.ts
Testing with ints and floats as well.
=> test(monitoring-exporter): add snapshot tests for all instruments

packages/opentelemetry-cloud-monitoring-exporter/__snapshots__/instrument-snapshot.test.ts.js, packages/opentelemetry-cloud-monitoring-exporter/src/external-types.ts, packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts, packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts, packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts
Also removed the display name prefix. The OTel metric name without the
GCM metric prefix is now used for display name.
Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/386
=> fix(monitoring-exporter)!: use workload.googleapis.com as default metric prefix

packages/opentelemetry-cloud-monitoring-exporter/__snapshots__/instrument-snapshot.test.ts.js, packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts, packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts, packages/opentelemetry-cloud-monitoring-exporter/test/instrument-snapshot.test.ts, packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts, packages/opentelemetry-cloud-monitoring-exporter/test/util.ts
This makes the exporter work with views (see included snapshot test), where the data point type will not match the instrument type. Otherwise the behavior of the exporter is unchanged.
Note the `InstrumentDescriptor.name` is still the only place to get the metric's name and it actually will match the name configured for output in the view. This is confusing, discussion going on in https://github.com/open-telemetry/opentelemetry-js/issues/3439
=> fix(monitoring-exporter): convert to GCM format based on metric data type, not instrument type

packages/opentelemetry-cloud-monitoring-exporter/__snapshots__/instrument-snapshot.test.ts.js, packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts, packages/opentelemetry-cloud-monitoring-exporter/test/instrument-snapshot.test.ts
This feature creates high cardinality by default. If users want this feature, they should set `service.*` resource labels to create a globally unique triple as described [in the spec](https://opentelemetry.io/docs/reference/specification/resource/semantic_conventions/#service:~:text=%5B3%5D%3A%20MUST%20be%20unique%20for%20each%20instance%20of%20the%20same%20service.namespace%2Cservice.name%20pair%20(in%20other%20words%20service.namespace%2Cservice.name%2Cservice.instance.id%20triplet%20MUST%20be%20globally%20unique)).
This will be possible once https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/459 is fixed.
=> fix(monitoring-exporter)!: remove auto generated task ID label from metrics

packages/opentelemetry-cloud-monitoring-exporter/__snapshots__/instrument-snapshot.test.ts.js, packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts, packages/opentelemetry-cloud-trace-exporter/src/transform.ts, packages/opentelemetry-cloud-trace-exporter/test/transform.test.ts, packages/opentelemetry-resource-util/.eslintignore, packages/opentelemetry-resource-util/__snapshots__/index.test.ts.js, packages/opentelemetry-resource-util/package-lock.json, packages/opentelemetry-resource-util/package.json, packages/opentelemetry-resource-util/src/index.ts, packages/opentelemetry-resource-util/test/index.test.ts
This changes the logic to select a monitored resource for populating GCM monitored resource and the special `g.co/{type}/{label}` span labels to match the Go/collector exporter impl.
I don't expect this change to have a big negative impact on users even though it changes the behavior a bit–we never declared the resource mapping/detection stable anyway.
=> feat: implement resource mapping for all supporter monitored resource types

packages/opentelemetry-cloud-monitoring-exporter/__snapshots__/instrument-snapshot.test.ts.js, packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts, packages/opentelemetry-cloud-monitoring-exporter/test/instrument-snapshot.test.ts, packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts, packages/opentelemetry-cloud-monitoring-exporter/test/transform.test.ts
Includes normalizing label keys so they properly work with Cloud Monitoring.
=> fix(monitoring-exporter): add LabelDescriptors to metric descriptor

packages/opentelemetry-cloud-trace-exporter/src/trace.ts
Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/465
I tested this manually with a local grpc server and see `user-agent: opentelemetry-js 1.8.0; google-cloud-trace-exporter 1.2.0 grpc-node-js/1.7.3` in metadata. I couldn't think of a quick and easy way to have an automated test.
=> fix(trace-exporter): correctly set user agent with grpc options

packages/opentelemetry-resource-util/package-lock.json, packages/opentelemetry-resource-util/package.json, packages/opentelemetry-resource-util/src/detector/detector.ts, packages/opentelemetry-resource-util/src/detector/gce.ts, packages/opentelemetry-resource-util/src/detector/gke.ts, packages/opentelemetry-resource-util/src/index.ts, packages/opentelemetry-resource-util/test/detector/detector.test.ts, packages/opentelemetry-resource-util/test/detector/gce.test.ts, packages/opentelemetry-resource-util/test/detector/gke.test.ts
Implements the resource detection methods for GKE and GCE, copied from https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/tree/v1.8.0/detectors/gcp.
Added a Detector which implements the resource detection interface to glue everything together. I will add the other detectors in separate PRs.
Verified this is working with e2e test in next PR https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/pull/468
=> feat(resource-util): detect GKE and GCE resource attributes

packages/opentelemetry-cloud-monitoring-exporter/__snapshots__/instrument-snapshot.test.ts.js, packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts
Fixes #473 
The `package-lock.json` file was not in sync with `package.json` when I went to make this change.  `npm ci` reported:
```
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Missing: @google-cloud/opentelemetry-resource-util@1.2.0 from lock file
```
I had to `npm i` to resolve the issue, which is the reason for the `package-lock.json` changes.  I can revert this change if you'd like, but it seems like the lock file was invalid, so that should probably be fixed.
=> fix(monitoring-exporter): use correct value type for histogram/distribution metrics

packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json
Addresses this comment https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/pull/474#issuecomment-1353761243
=> chore(monitoring-exporter): add @opentelemetry/sdk-metrics as an explicit dev dependency

e2e-test-server/Dockerfile
Was failing because it was a different lerna version than specified in the `package.json`. Running `npm install` before `npx lerna ...` makes it use the locally installed version. # Please enter the commit message for your changes. Lines starting
=> chore: fix e2e Dockerfile build issue

.github/workflows/ci.yaml, e2e-test-server/package-lock.json, e2e-test-server/package.json, package-lock.json, package.json, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-propagator/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package.json, packages/opentelemetry-resource-util/package-lock.json, packages/opentelemetry-resource-util/package.json, samples/trace/package-lock.json, samples/trace/package.json
Fixes #476
Question for the group, should we consider this a breaking change and do major version bumps on stable packages?
=> chore!: drop support for node 10 and 12

cloudbuild-e2e-cloud-functions-gen2.yaml, e2e-test-server/package-lock.json, e2e-test-server/package.json, e2e-test-server/src/constants.ts, e2e-test-server/src/index.ts, packages/opentelemetry-resource-util/src/detector/detector.ts
One small tweak in ordering of resource checks was needed to make this work. Probably need the same change in opentelemetry-operations-go.
Otherwise, got monorepo working with Cloud Functions by packing the dependency sources into tarballs (with `npm pack`) and including that in the zip source.
=> feat: run e2e tests on Cloud Functions

cloudbuild-e2e-gae.yaml, e2e-test-server/src/index.ts, packages/opentelemetry-resource-util/__snapshots__/index.test.ts.js, packages/opentelemetry-resource-util/src/detector/detector.ts, packages/opentelemetry-resource-util/src/detector/gae.ts, packages/opentelemetry-resource-util/src/index.ts, packages/opentelemetry-resource-util/test/detector/detector.test.ts, packages/opentelemetry-resource-util/test/detector/gae.test.ts, packages/opentelemetry-resource-util/test/index.test.ts
=> feat(resource-util): add App Engine detector

.dockerignore, .gitignore, cloudbuild-e2e-cloud-functions-gen2.yaml, e2e-test-server/Dockerfile, e2e-test-server/package-lock.json, e2e-test-server/package.json
Container sizes are much smaller:
This reduction in layer size makes e2e tests faster by reducing the amount to be uploaded/downloaded and compressed/decompressed. Build time is reduced by ~1 minute.
=> test: use @vercel/ncc to bundle e2e-test-server and eliminate dead code for smaller containers

e2e-test-server/src/scenarios.ts, packages/opentelemetry-resource-util/src/index.ts
This is in order to cut a new release (https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/509) but at this point we haven't decided on some strategies with new resource detector. For now, we can just hide it and postpone the decision until the subsequent release.
=> chore: un-export the unreleased resource detector until after the next release

e2e-test-server/src/scenarios.ts, packages/opentelemetry-resource-util/src/index.ts
Reverts GoogleCloudPlatform/opentelemetry-operations-js#519
Decided we don't actually need this since the next release will be a major version bump regardless.
=> Revert "chore: un-export the unreleased resource detector until after the next release"

packages/opentelemetry-resource-util/src/detector/gce.ts, packages/opentelemetry-resource-util/test/detector/detector.test.ts, packages/opentelemetry-resource-util/test/detector/gce.test.ts
This is a bug. See Go impl https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/a62ae2cc5958c5ea59cbc9064cd4a76a4af25da9/detectors/gcp/gce.go#L43
=> fix: detect OTel host.name property from instance/name instead of hostname

e2e-test-server/src/scenarios.ts, packages/opentelemetry-resource-util/src/detector/detector.ts, packages/opentelemetry-resource-util/src/index.ts, packages/opentelemetry-resource-util/test/detector/detector.test.ts
For more context, this new interface was added upstream (and the old one deprecated) so that resource detection will be "synchronous" and the SDK initialization can complete before any other code runs. For auto instrumentation, this is important so that monkey patching is finished before the user imports anything.
The deprecated `GcpDetector` will be removed in the next major version
=> feat(resource-util): implement the DetectorSync resource detector interface

cloudbuild-e2e-cloud-functions-gen2.yaml, cloudbuild-e2e-cloud-run.yaml, cloudbuild-e2e-gae.yaml, cloudbuild-e2e-gce.yaml, cloudbuild-e2e-gke.yaml, cloudbuild-e2e-local.yaml, packages/opentelemetry-resource-util/src/detector/detector.ts, packages/opentelemetry-resource-util/src/detector/faas.ts, packages/opentelemetry-resource-util/src/index.ts, packages/opentelemetry-resource-util/test/detector/detector.test.ts, packages/opentelemetry-resource-util/test/detector/faas.test.ts, packages/opentelemetry-resource-util/test/index.test.ts
Part of https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/679
=> fix: use faas.instance instead of faas.id in resource detectors

.github/trusted-contribution.yml
See trusted contribution app documentation https://github.com/googleapis/repo-automation-bots/tree/main/packages/trusted-contribution. This config will make the bot comment `/gcbrun` on Renovate's PRs so the tests will automatically start.
I just installed the bot on this repo.
=> chore: setup Trusted Contribution bot to add /gcbrun on renovate PRs

samples/trace/index.js
Calling `provider.register()` calls `setGlobalTracerProvider` and also does some additional tweaking that makes context propagation work properly. Even though this sample doesn't do context propagation, this would save developers headache when they're copying and pasting the setup from this example and wondering why their propagators aren't working with instrumented libraries (which is what happened with me).
=> Use provider.register instead of setGlobalTraceProvider

.github/workflows/ci.yaml
This fixes the build which is currently broken because `npm@latest` (v10) doesn't work with anything older than Node 20
=> chore(build): stop installing latest npm which doesn't support old nodejs versions

packages/opentelemetry-cloud-trace-exporter/src/transform.ts, packages/opentelemetry-resource-util/src/index.ts
Fixes #553
Deprecate the `includeUnsupportedResources` parameter by splitting the function def into a deprecated and non-deprecated overload. It is no longer needed as we decide that trace and monitoring exporters should do the exact same resource mapping. The package is marked stable so I full removal would be a breaking change.
This is equivalent to what we do in [Go](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/v0.44.0/internal/resourcemapping/resourcemapping.go) and Java https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/pull/250
=> feat(trace-exporter): use the same resource mapping for metrics and traces

packages/opentelemetry-resource-util/__snapshots__/index.test.ts.js, packages/opentelemetry-resource-util/src/index.ts, packages/opentelemetry-resource-util/test/index.test.ts
Fixes #641
Pretty much copied from https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/273
=> feat(resource-util): use faas resource attributes as fallbacks for service.* attributes

packages/opentelemetry-cloud-trace-exporter/README.md, samples/trace/index.js
We don't ever recommend using `SimpleSpanProcessor` because of poor performance and large number of API requests. Remove it from our sample (which goes to [this doc](https://cloud.google.com/trace/docs/setup/nodejs-ot#gke)) and README
=> chore: remove SimpleSpanProcessor from README and sample

package-lock.json, samples/otlptracehttp/app.js, samples/otlptracehttp/dice.js, samples/otlptracehttp/package.json
To run:
```
export OTEL_RESOURCE_ATTRIBUTES="gcp.project_id=<project-id>"
export OTEL_EXPORTER_OTLP_ENDPOINT=<endpoint>
node app.js
```
In another terminal
```
curl localhost:8080/rolldice?rolls=12
```
(or any number of rolls)
Samples heavily based on OTel docs at https://opentelemetry.io/docs/languages/js/getting-started/nodejs, so adding their copyright as well
=> Add OTLP trace http sample with Google auth

renovate.json, samples/instrumentation-quickstart/package-lock.json, samples/instrumentation-quickstart/package.json, samples/instrumentation-quickstart/src/index.ts
- Downgrade fastify to 4.23.2 as that is the last version supporting Typescript v4. This was accidentally upgraded in https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/pull/689
- Add a renovate rule to split out fastify upgrades since it can't be upgraded right now
- Small tweaks to comments and logging code
=> docs: added a few fixes for the quickstart sample

samples/instrumentation-quickstart/otel-collector-config.yaml
Similar to https://github.com/GoogleCloudPlatform/golang-samples/pull/3999, this makes the collector parse severity strings the same way the Cloud Logging agent does. The app already outputs the correct severity strings.
Tested manually by logging at various levels
=> docs(instrumentation-quickstart): fix collector severity parsing to match Cloud Logging agent

package-lock.json, samples/otlptracegrpc/.prettierrc.js, samples/otlptracegrpc/README.md, samples/otlptracegrpc/app.ts, samples/otlptracegrpc/client.ts, samples/otlptracegrpc/dice.ts, samples/otlptracegrpc/package.json, samples/otlptracegrpc/tsconfig.json
Adds sample for otlp trace export via grpc export. The credentials are added on a per call basis and auto-refresh.
- Ran the sample app continuously for roughly 2 hours and generated spans at a constant rate.
*Inspired by the existing [otlp-trace sample](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/pull/678). Adjusted copyrights accordingly.*
=> feat: Add sample for otlp-trace export via grpc

samples/otlptraceexport/package.json
This brings the sample in line with other typescript code in this repo that use `pretest` script to make sure everything compiles in CI. Since the sample has no tests, I've left the actual test script empty (test test runner fails if it finds no tests)
=> chore(otlptraceexport): add empty test script so sample is compiled in CI

package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/README.md, packages/opentelemetry-resource-util/package.json, packages/opentelemetry-resource-util/src/detector/detector.ts, packages/opentelemetry-resource-util/src/index.ts, samples/otlptraceexport/package.json
[Since v1.22.0](https://github.com/open-telemetry/opentelemetry-js/blob/main/CHANGELOG.md#rocket-enhancement-3), the semantic conventions package exports individual strings and deprecated the object namespace approach. Note, this is not a breaking change or affect our support in any way.
=> chore: update usage of @opentelemetry/semantic-conventions to avoid deprecated namespaces

packages/opentelemetry-resource-util/src/detector/detector.ts, packages/opentelemetry-resource-util/src/detector/gae.ts, packages/opentelemetry-resource-util/test/detector/gae.test.ts
Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/655
It turns out GAE standard environment's metadata server returns a zone string like `projects/myproject/zones/us15`. ut integration tests only run on AppEngine flex not standard so this wasn't caught 🙁. Here are HTTP logs I printed out from a sample app:
```json
{
"jsonPayload": {
"message": "gaxios metadata request",
"responseData": "projects/<project>/zones/us15",
"requestUrl": "http://169.254.169.254/computeMetadata/v1/instance/zone"
},
"resource": {
"type": "gae_app",
"labels": {
"zone": "us15",
"version_id": "20240503t222051",
"project_id": "otel-starter-project",
"module_id": "default"
}
}
}
```
I updated the tests and manually tested a sample app on GAE standard writing metrics: 
---
I think this bug …
=> fix(resource-detector): properly detect zone on AppEngine standard

cloudbuild-e2e-cloud-run.yaml, cloudbuild-e2e-gae-standard.yaml, cloudbuild-e2e-gae.yaml, cloudbuild-e2e-gce.yaml, cloudbuild-e2e-gke.yaml, cloudbuild-e2e-local.yaml, e2e-test-server/fake.package.json
The yaml is mostly copied from the Cloud Functions config which also outputs a zip file.
=> test: run e2e tests on GAE standard

samples/instrumentation-quickstart/tsconfig.json, samples/otlptraceexport/tsconfig.json
By fixing the `extends` to be the same. Previous versions of typescript required a path but now an NPM import path works. For the e2e-test package, i had to leave as is because ncc breaks and I don't have time to look into it.
=> chore: fix tsconfigs to all be the same

cloudbuild-e2e-cloud-functions-gen2.yaml, cloudbuild-e2e-cloud-run.yaml, cloudbuild-e2e-gae-standard.yaml, cloudbuild-e2e-gae.yaml, cloudbuild-e2e-gce.yaml, cloudbuild-e2e-gke.yaml, cloudbuild-e2e-image.yaml, cloudbuild-e2e-local.yaml, e2e-test-server/wait-for-image.sh
- Push images to GAR
- Upgrading to latest test runner docker image which lives in GAR
- Update `wait-for-image.sh` and build scripts that were coupled to gcr.
=> chore: migrate e2e tests Container Registry usage to Artifact Registry

samples/instrumentation-quickstart/docker-compose.yaml, samples/instrumentation-quickstart/otel-collector-config.yaml, samples/instrumentation-quickstart/package-lock.json
Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/744
- Regenerated a `package-lock.json`
- `$FOO` -> `${FOO}`
- OTLP listen on `0.0.0.0` (the default was changed to localhost)
Manually tested. Really should get some automated tests created for this.
=> fix(samples/instrumentation-quickstart): fix breakages in quickstart

.github/workflows/ci.yaml, .nycrc, package-lock.json, package.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-propagator/package.json, packages/opentelemetry-resource-util/package.json
Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/755
This is the recommend codecov setup, instead of using the deprecated codecov npm package which is breaking CI. Details in https://about.codecov.io/blog/codecov-uploader-deprecation-plan/
=> chore: migrate to codecov Github action

e2e-test-server/package-lock.json, e2e-test-server/package.json, package-lock.json, samples/instrumentation-quickstart/package-lock.json, samples/instrumentation-quickstart/package.json, samples/otlptraceexport/package.json
Express is used in samples. There is a vulnerability in a transitive dep that this fixes.
=> chore(deps): bump express to 4.21.0

packages/opentelemetry-cloud-trace-exporter/package.json
This fixes the issue of https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/768 but I will leave it open until I make a new patch release
NPM pack now includes the `protos.json` in the tarball:
```sh
$ npm pack
npm notice
npm notice 📦  @google-cloud/opentelemetry-cloud-trace-exporter@2.4.0
npm notice === Tarball Contents ===
npm notice 11.4kB  LICENSE
npm notice 4.3kB   README.md
npm notice 117.9kB build/protos/protos.json
npm notice 1.5kB   build/src/external-types.d.ts
npm notice 707B    build/src/external-types.js
npm notice 59B     build/src/index.d.ts
npm notice 1.5kB   build/src/index.js
npm notice 1.2kB   build/src/trace.d.ts
npm notice 6.0kB   build/src/trace.js
npm notice 268B    build/src/transform.d.ts
npm notice 8.6kB   build/src/transform.js
npm notice …
```
=> fix(trace-exporter): include protos.json in the npm pack tarball

samples/instrumentation-quickstart/docker-compose.yaml, samples/instrumentation-quickstart/otel-collector-config.yaml, samples/instrumentation-quickstart/src/instrumentation.ts
Same as https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/364.
This also updates the collector version.
Since the environment variable isn't supported yet, I had to add this as an option to the OTLP exporter.
=> feat: use exponential histograms for the quickstart sample

.github/workflows/ci.yaml, README.md, cloudbuild-e2e-cloud-functions-gen2.yaml, e2e-test-server/package.json, package.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-propagator/package.json, packages/opentelemetry-resource-util/package.json, samples/instrumentation-quickstart/package.json, samples/metrics/package.json, samples/otlpmetricexport/package.json, samples/otlptraceexport/package.json, samples/trace/package.json, scripts/package.json
Unblocks https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/630 and https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/pull/791/
BREAKING CHANGE: removes support for older Node.js versions in `package.json` engines and CI jobs.
=> chore!: drop support for EOL Node.js versions <18
