package.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/README.md, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/src/external-types.ts, packages/opentelemetry-cloud-trace-exporter/src/trace.ts, packages/opentelemetry-cloud-trace-exporter/src/transform.ts, packages/opentelemetry-cloud-trace-exporter/test/exporter.test.ts, packages/opentelemetry-cloud-trace-exporter/test/transform.test.ts
/cc @dancalvert-google @kintel
=> chore: rename stackdriver to Google Cloud Trace

packages/opentelemetry-cloud-trace-exporter/package.json
=> Bump opentelemetry from 0.5.0 to 0.6.0 in Trace exporter

lerna.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/src/version.ts, samples/trace/package.json
Release draft notes: https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/releases/tag/untagged-e8d019f283b58f4a8575
=> chore: 0.2.0 release proposal

packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-monitoring-exporter/src/external-types.ts, packages/opentelemetry-cloud-monitoring-exporter/src/index.ts, packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts, packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts, packages/opentelemetry-cloud-monitoring-exporter/src/types.ts, packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts, packages/opentelemetry-cloud-monitoring-exporter/test/transform.test.ts
Fixes #9 and follow-up of #16
~This is a _work in progress_, feel free to add comments (if you have any).~
=> feat: add cloud monitoring exporter

lerna.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/package.json, samples/trace/package.json
Release notes: https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/releases/tag/untagged-2e4ae09d9e5829301b01
=> chore: 0.3.0 release proposal

packages/opentelemetry-cloud-monitoring-exporter/README.md
=> Adding npm-url in README.md

docs/contributing.md
=> Adding content in contributing.md file

.github/ISSUE_TEMPLATE/bug_report.md
=> Adding bug_report file in opentelemetry-operations-js

.github/ISSUE_TEMPLATE/feature_request.md
=> chore: adding feature_request .md file

.github/PULL_REQUEST_TEMPLATE.md
=> Adding PULL_REQUEST_TEMPLATE.md file .

packages/opentelemetry-cloud-trace-propagator/README.md
=> chore: add README.md for opentelemetry-cloud-trace-propagator

.circleci/config.yml
Fixes #<issue_number_goes_here>
=> chore: add node 14 job

packages/opentelemetry-cloud-trace-propagator/package.json
=> chore: add publishConfig

packages/opentelemetry-cloud-trace-propagator/src/index.ts
=> chore: export CloudPropagator module

packages/opentelemetry-cloud-trace-propagator/README.md
=> chore: update opentelemetry-cloud-trace-propagator README.md

lerna.json, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-propagator/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package.json
Release draft notes: https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/releases/tag/untagged-90e28f00e8c92cf61dbe
=> chore: 0.4.0 release proposal

package.json, packages/opentelemetry-cloud-trace-propagator/package.json
=> fix: Cloud propagator package is missing one file and breaks compilation

lerna.json, package-lock.json, package.json, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-propagator/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package.json
Draft tag https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/releases/edit/untagged-010a0fce1d63a818d6c3
=> chore: 0.4.1 release proposal

package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-propagator/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package.json
Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/112
=> feat: Move OpenTelemetry SDK dependency to peer dependency

.circleci/config.yml
- Use new CircleCI convenience images
(https://circleci.com/docs/2.0/circleci-images/#next-gen-circleci-images)
- Use job parameters instead of yaml anchors
- Remove NPM_CONFIG_UNSAFE_PERM flag for running as root (was needed for
node:* images, I believe)
- Remove bash logic, use [CircleCI conditional steps](https://circleci.com/docs/2.0/configuration-reference/#the-when-step-requires-version-21)
Fixes #163
=> ci: clean up circle ci config

lerna.json, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-propagator/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package.json
https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/releases/edit/untagged-d9450432aa019e83e563
=> chore: 0.4.3 release proposal

lerna.json, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-propagator/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package.json, samples/trace/package-lock.json, samples/trace/package.json
Release draft https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/releases/edit/untagged-4e58df41dffd4bdfac39
=> chore: 0.6.0 release proposal

package-lock.json, samples/trace/package-lock.json
The sample one somehow got into a bad state. Also updating the repo root lerna one, because of security vulnerability.
=> chore: update package-lock.json files

lerna.json, package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-propagator/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package.json, samples/trace/package-lock.json, samples/trace/package.json
Release draft: https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/releases/edit/untagged-0cb69d68f5ab5ab993ac
=> chore: 0.8.0 release proposal

lerna.json, package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/src/version.ts, packages/opentelemetry-cloud-trace-propagator/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package.json, samples/trace/package-lock.json, samples/trace/package.json
Release notes and future tag: https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/releases/edit/untagged-b85e81ff2cca9c629f3b
Release instructions [here](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/master/docs/releasing.md) for reference
=> chore: 0.9.0 release proposal

packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/src/transform.ts, packages/opentelemetry-cloud-trace-exporter/test/transform.test.ts, packages/opentelemetry-cloud-trace-propagator/package-lock.json, samples/trace/package-lock.json
Fixes #267 
BREAKING CHANGE: spans will no longer have project id attribute
=> feat: stop adding project id to span attributes

package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package-lock.json
```bash
$ npm audit fix
$ npx lerna exec npm -- audit fix --force
```
You can ignore the Cloud Build errors, its WIP
=> chore: npm audit fix

packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-propagator/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package.json, samples/trace/package-lock.json, samples/trace/package.json
Latest versions now that 0.22 is released
=> chore: upgrade to otel api 1.0.0, sdk 0.22.0

e2e-test-server/package-lock.json, e2e-test-server/package.json, lerna.json, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/src/version.ts, packages/opentelemetry-cloud-trace-propagator/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package.json, packages/opentelemetry-resource-util/package-lock.json, packages/opentelemetry-resource-util/package.json, samples/trace/package-lock.json, samples/trace/package.json
https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/releases/edit/untagged-ac4dd6e8d1d55875d481
=> chore: 0.11.0 release proposal

packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts
=> fix: always use forward slash when creating MetricDescriptor name and type

e2e-test-server/package-lock.json, e2e-test-server/package.json, lerna.json, packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/package-lock.json, packages/opentelemetry-cloud-trace-exporter/package.json, packages/opentelemetry-cloud-trace-exporter/src/version.ts, packages/opentelemetry-cloud-trace-propagator/package-lock.json, packages/opentelemetry-cloud-trace-propagator/package.json, packages/opentelemetry-resource-util/package-lock.json, packages/opentelemetry-resource-util/package.json, samples/trace/package-lock.json, samples/trace/package.json
Draft release: https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/releases/edit/untagged-33a0d31d7a4142b2bca4
=> chore: 0.12.0 release proposal

packages/opentelemetry-cloud-monitoring-exporter/package-lock.json, packages/opentelemetry-cloud-monitoring-exporter/package.json, packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts, packages/opentelemetry-cloud-monitoring-exporter/test/monitoring.test.ts, packages/opentelemetry-cloud-monitoring-exporter/test/transform.test.ts
=> chore(monitoring): upgrade to @opentelemetry/api-metrics@0.27.0

packages/opentelemetry-cloud-trace-exporter/src/external-types.ts, packages/opentelemetry-cloud-trace-exporter/src/trace.ts, packages/opentelemetry-cloud-trace-exporter/src/transform.ts, packages/opentelemetry-cloud-trace-exporter/test/transform.test.ts
Fixes #440 (sort of, at least until proper API level support for array types is added to CloudTrace)
=> feat: export array type attributes

.github/workflows/ci.yaml
=> chore: set npm major version per node version in CI

packages/opentelemetry-cloud-trace-exporter/src/transform.ts, packages/opentelemetry-resource-util/__snapshots__/index.test.ts.js, packages/opentelemetry-resource-util/src/detector/detector.ts, packages/opentelemetry-resource-util/src/detector/faas.ts, packages/opentelemetry-resource-util/src/index.ts, packages/opentelemetry-resource-util/test/detector/detector.test.ts, packages/opentelemetry-resource-util/test/detector/faas.test.ts, packages/opentelemetry-resource-util/test/index.test.ts
Copied from the Go impl.
E2E tests are also passing in follow up PR https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/pull/480
=> feat(resource-util): add support to detect Cloud Run and Cloud Functions

.github/CODEOWNERS
This should auto-assign the review group when a PR is opened.
=> chore: add CODEOWNERS file to repo

packages/opentelemetry-cloud-monitoring-exporter/__snapshots__/instrument-snapshot.test.ts.js, packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts, packages/opentelemetry-cloud-monitoring-exporter/src/utils.ts, packages/opentelemetry-cloud-monitoring-exporter/test/instrument-snapshot.test.ts, packages/opentelemetry-cloud-monitoring-exporter/test/transform.test.ts
Fixes #555
Copied the implementation from the collector exporter and added tests. Note this is not super useful until https://github.com/open-telemetry/opentelemetry-js/issues/3931 is fixed and released.
=> feat(monitoring): implement ExponentialHistogram exporting

samples/instrumentation-quickstart/README.md
Updates README as per https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/pull/315#pullrequestreview-1961678744.
=> Update instrumentation-quickstart README

samples/instrumentation-quickstart/package-lock.json
This was accidentally deleted in https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/pull/690
=> chore(docs): restore accidentally deleted package-lock.json

packages/opentelemetry-resource-util/__snapshots__/index.test.ts.js, packages/opentelemetry-resource-util/src/index.ts, packages/opentelemetry-resource-util/test/index.test.ts
=> fix: #594 enable mapping when not gcp kubernetes

packages/opentelemetry-cloud-monitoring-exporter/__snapshots__/instrument-snapshot.test.ts.js, packages/opentelemetry-cloud-monitoring-exporter/src/external-types.ts, packages/opentelemetry-cloud-monitoring-exporter/src/monitoring.ts, packages/opentelemetry-cloud-monitoring-exporter/test/instrument-snapshot.test.ts
=> feat: allow setting a custom user agent and version.
